[2024-11-12T14:48:56.863+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-12T14:48:56.893+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_kimdong_dag.scrapy_crawl_to_mongodb manual__2024-11-12T14:48:55.309411+00:00 [queued]>
[2024-11-12T14:48:56.908+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_kimdong_dag.scrapy_crawl_to_mongodb manual__2024-11-12T14:48:55.309411+00:00 [queued]>
[2024-11-12T14:48:56.909+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-12T14:48:56.925+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): scrapy_crawl_to_mongodb> on 2024-11-12 14:48:55.309411+00:00
[2024-11-12T14:48:56.937+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=209) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T14:48:56.935+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_kimdong_dag', 'scrapy_crawl_to_mongodb', 'manual__2024-11-12T14:48:55.309411+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/test_main.py', '--cfg-path', '/tmp/tmpq62wqp9t']
[2024-11-12T14:48:56.938+0000] {standard_task_runner.py:72} INFO - Started process 210 to run task
[2024-11-12T14:48:56.939+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask scrapy_crawl_to_mongodb
[2024-11-12T14:48:56.962+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-12T14:48:57.010+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_kimdong_dag.scrapy_crawl_to_mongodb manual__2024-11-12T14:48:55.309411+00:00 [running]> on host e0225847bbdb
[2024-11-12T14:48:57.136+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_kimdong_dag' AIRFLOW_CTX_TASK_ID='scrapy_crawl_to_mongodb' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T14:48:55.309411+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T14:48:55.309411+00:00'
[2024-11-12T14:48:57.138+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-12T14:48:57.214+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-12T14:48:57.218+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        docker build -t kimdong_scraper -f /opt/airflow/DeTaiPhanTichDinhLuong_Xuly_Pyspark_WebKimDong_BanChinh/DeTai_PhanTichDinhLuong_WebKimDong-main_version2_pyspark_windows/Dockerfile .\n        docker container run -e Mongo_HOST=mymongodb_container --network my_network --name kimdong_scraper kimdong_scraper\n    ']
[2024-11-12T14:48:57.230+0000] {subprocess.py:99} INFO - Output:
[2024-11-12T14:48:57.368+0000] {subprocess.py:106} INFO - DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
[2024-11-12T14:48:57.369+0000] {subprocess.py:106} INFO -             Install the buildx component to build images with BuildKit:
[2024-11-12T14:48:57.370+0000] {subprocess.py:106} INFO -             https://docs.docker.com/go/buildx/
[2024-11-12T14:48:57.371+0000] {subprocess.py:106} INFO - 
[2024-11-12T14:48:57.419+0000] {subprocess.py:106} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-11-12T14:48:57.436+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2024-11-12T14:48:57.439+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2024-11-12T14:48:57.440+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2024-11-12T14:48:57.457+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2024-11-12T14:48:57.469+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_kimdong_dag, task_id=scrapy_crawl_to_mongodb, run_id=manual__2024-11-12T14:48:55.309411+00:00, execution_date=20241112T144855, start_date=20241112T144856, end_date=20241112T144857
[2024-11-12T14:48:57.483+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-12T14:48:57.485+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task scrapy_crawl_to_mongodb (Bash command failed. The command returned a non-zero exit code 125.; 210)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2024-11-12T14:48:57.529+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-12T14:48:57.555+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T14:48:57.559+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
